language: python

python:
    - "2.7"

install:
    - source configure

script:
    - py.test -vs src tests/commoncode tests/extractcode tests/textcode tests/typecode tests/cluecode tests/licensedcode/test_detect.py tests/licensedcode/test_index.py tests/licensedcode/test_legal.py tests/licensedcode/test_models.py

