environment:
    matrix:
        - TEST_SUITE: "py.test -vvs --reruns 3 -n2 --ignore=tests/scancode"
        - TEST_SUITE: "py.test -vvs --reruns 3     tests/scancode"

install:
    - configure

build: off


test_script:
    - python -c "import sys;print(sys.getdefaultencoding())"
    - cmd: "%TEST_SUITE%"
