version: '{build}'

environment:
    matrix:
        - TEST_SUITE: "py.test -n 2 -vvs --test-suite=all --ignore=tests/scancode --ignore=tests/extractcode --ignore=tests/licensedcode --ignore=tests/cluecode --ignore=tests/packagedcode"
        - TEST_SUITE: "py.test -n 2 -vvs --test-suite=all tests/scancode  --reruns 1"
        - TEST_SUITE: "py.test -n 2 -vvs --test-suite=all tests/extractcode"
        - TEST_SUITE: "py.test -n 2 -vvs --test-suite=all tests/licensedcode --ignore=tests/licensedcode/test_zzzz_cache.py  --ignore=tests/licensedcode/test_detection_datadriven.py"
        - TEST_SUITE: "py.test -n 2 --test-suite=all tests/licensedcode/test_detection_datadriven.py -k TestLicenseDataDriven"
        - TEST_SUITE: "py.test -n 2 --test-suite=all tests/licensedcode/test_detection_datadriven.py -k TestLicenseRetrographyDataDriven"
        - TEST_SUITE: "py.test -n 2 --test-suite=all tests/licensedcode/test_detection_datadriven.py -k TestLicenseSpdxDataDriven"
        - TEST_SUITE: "py.test -n 2 --test-suite=all tests/licensedcode/test_detection_datadriven.py -k TestLicenseToolsDataDriven"
        - TEST_SUITE: "py.test -n 2 --test-suite=all tests/licensedcode/test_detection_datadriven.py -k TestSlicDataDriven"
        - TEST_SUITE: "py.test -n 2 --test-suite=all tests/licensedcode/test_detection_datadriven.py -k TestFossLicDataDriven"
        - TEST_SUITE: "py.test -n 2 --test-suite=all tests/licensedcode/test_detection_datadriven.py -k TestDebLicCheckTestsDataDriven"
        - TEST_SUITE: "py.test -vvs --test-suite=all tests/licensedcode/test_zzzz_cache.py --reruns 1"
        - TEST_SUITE: "py.test -n 2 --test-suite=all -s tests/cluecode"
        - TEST_SUITE: "py.test -n 2 --test-suite=all -s tests/packagedcode"

install:
    - configure

build: off


test_script:
    - python -c "import sys;print sys.getdefaultencoding()"
    - cmd: "%TEST_SUITE%"

on_failure:
    - "python etc/scripts/irc-notify.py aboutcode [{project_name}:{branch}] {short_commit}: \"{message}\" ({author}) {color_red}Failed - {build_url}"
