version: '{build}'

environment:
    matrix:
        - TEST_SUITE: "py.test -n 2 -vvs tests/scancode"
        - TEST_SUITE: "py.test -n 2 -vvs tests/extractcode"
        - TEST_SUITE: "py.test -n 2 -s tests/licensecode"
        - TEST_SUITE: "py.test -n 2 -s tests/cluecode"
        - TEST_SUITE: "py.test -n 2 -s tests/packagedcode"
        - TEST_SUITE: "py.test -n 2 -s --ignore=tests/scancode --ignore=tests/extractcode --ignore=tests/licensecode --ignore=tests/cluecode --ignore=tests/packagedcode"

install:
    - configure

build: off


test_script:
    - python -c "import sys;print sys.getdefaultencoding()"
    - cmd: "%TEST_SUITE%"

on_success:
    - "python etc/scripts/irc-notify.py aboutcode [{project_name}:{branch}] {short_commit}: \"{message}\" ({author}) {color_green}Succeeded,Details: {build_url},Commit: {commit_url}"

on_failure:
    - "python etc/scripts/irc-notify.py aboutcode [{project_name}:{branch}] {short_commit}: \"{message}\" ({author}) {color_red}Failed,Details: {build_url},Commit: {commit_url}"
