trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
  - job: TEST
    displayName: Performing test 
    steps:
      - script: ./configure
      - script: ./bin/py.test -vvs tests/commoncode
