parameters:
    job_name: ''
    image_name: 'ubuntu-16.04'
    container: ''
    python_path: ''
    python_version: ''
    package_manager: apt-get
    install_python: ''
    install_packages: |
        set -e -x
        sudo apt-get -y update
        sudo apt-get -y install \
            build-essential \
            xz-utils zlib1g bzip2 libbz2-1.0 tar \
            sqlite3 libxml2-dev libxslt1-dev \
            software-properties-common openssl
    test_suites:
        commoncode: bin/py.test -vvs tests/commoncode
        # scancode: bin/py.test -vvs --reruns=1 tests/scancode


jobs:
    - job: ${{ parameters.job_name }}

      pool:
          vmImage: ${{ parameters.image_name }}

      container:
          image: ${{ parameters.container }}
          options: '--name ${{ parameters.job_name }} -v /usr/bin/docker:/tmp/docker:ro'

      strategy:
          matrix:
              ${{ each tsuite in parameters.test_suites }}:
                 ${{ format('{0}', tsuite.key) }}:
                     test_suite_label: ${{ tsuite.key }}
                     test_suite: ${{ tsuite.value }}

      steps:
          - script: /tmp/docker exec -t -u 0 ${{ parameters.job_name }} $(Build.SourcesDirectory)/etc/ci/install_sudo.sh ${{ parameters.package_manager }}
            displayName: Install sudo

          - script: ${{ parameters.install_packages }}
            displayName: Install required packages

          - script: ${{ parameters.install_python }}
            displayName: 'Install Python ${{ parameters.python_version }}'

          - script: PYTHON_EXE=${{ parameters.python_path }} ./configure
            displayName: 'Run Configure'

          - script: $(test_suite)
            displayName: 'Run $(test_suite_label) tests with py${{ parameters.python_version }} on ${{ parameters.job_name }}'
